### ISSUE TITLE
Complie errors

### ISSUE THREAD

**Issue by ucelme** [basememara/BasemEmaraBlogIOS#15]
I downloaded and tried to compile your app, but get errors:

error: /Users/Library/Developer/Xcode/DerivedData/BasemEmara-bqvciuxssxnjsycjlikvmxldeyqi/SourcePackages/checkouts/SwiftyPress/Resources/SwiftyPress.bundle: No such file or directory (in target 'BasemEmara iOS Notification' from project 'BasemEmara')

error: /Users/Library/Developer/Xcode/DerivedData/BasemEmara-bqvciuxssxnjsycjlikvmxldeyqi/SourcePackages/checkouts/ZamzamKit/Resources/ZamzamCore.bundle: No such file or directory (in target 'BasemEmara iOS Notification' from project 'BasemEmara')

**Comment by basememara** [comment]
Can you try the latest `develop` branch, I did fix some things in that branch.
