### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by QurQuma** [basememara/BasemEmaraBlogIOS#5]
Hi,
I’m testing this app (great work, thanks!)
I’m not a developer and following steps I receive this error during compiling:

Build Failed
Task failed with exit code 65:
/usr/bin/xcrun xcodebuild -workspace /Users/qurquma/Documents/Sviluppo/Untitled/Carthage/Checkouts/SwiftyPress/SwiftyPress.xcworkspace -scheme SwiftyPress\ iOS -configuration Release -derivedDataPath /Users/qurquma/Library/Caches/org.carthage.CarthageKit/DerivedData/10.1_10B61/SwiftyPress/1.0.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/8j/n9s06w8178z3l0hsf82_nhch0000gn/T/SwiftyPress SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/qurquma/Documents/Sviluppo/Untitled/Carthage/Checkouts/SwiftyPress)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/8j/n9s06w8178z3l0hsf82_nhch0000gn/T/carthage-xcodebuild.8Mt50E.log

I really would like to test this app on my website to check out if this can work as an app for this and develop some further features with your work.
I would like to know some more about this:

- Is it possible to have an android app with same functionalities?
- Is this something you can do?
- Are you available in adding more features to this apps (offline pdf reading, woocommerce, pmpro membership…)?
- Cost approx

I’m here at your disposal for every question about build error and my request.
Bests,
Francesco

**Comment by basememara** [comment]
I've made some updates and upgraded Swift. Let me know if you're still having issues.

An Android version is something I've been thinking about, but is a big undertaking ;)
